<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
class SubCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sub_categories')->truncate();

        DB::table('sub_categories')->insert([
            ['name' => 'Gardening', 'category_id' => '1','created_at' => Carbon::now()],
            ['name' => 'Lawn care', 'category_id' => '1','created_at' => Carbon::now()],
            ['name' => 'Organizing', 'category_id' => '1','created_at' => Carbon::now()],
            ['name' => 'Becoming an Artist', 'category_id' => '2','created_at' => Carbon::now()],
            ['name' => 'Drawing', 'category_id' => '2','created_at' => Carbon::now()],
            ['name' => 'Fine Art', 'category_id' => '2','created_at' => Carbon::now()],
            ['name' => 'Cars', 'category_id' => '3','created_at' => Carbon::now()],
            ['name' => 'Trucks', 'category_id' => '3','created_at' => Carbon::now()],
            ['name' => 'Motorcycles', 'category_id' => '3','created_at' => Carbon::now()],
            ['name' => 'SUVs', 'category_id' => '3','created_at' => Carbon::now()],
            ['name' => 'RVs', 'category_id' => '3','created_at' => Carbon::now()],
            ['name' => 'Collectors', 'category_id' => '3','created_at' => Carbon::now()],
            ['name' => 'Mentoring', 'category_id' => '4','created_at' => Carbon::now()],
            ['name' => 'Choosing a Career', 'category_id' => '4','created_at' => Carbon::now()],
            ['name' => 'Getting Promoted', 'category_id' => '4','created_at' => Carbon::now()],
            ['name' => 'Navigating Work Politics', 'category_id' => '4','created_at' => Carbon::now()],
            ['name' => 'Job Interviews', 'category_id' => '4','created_at' => Carbon::now()],
            ['name' => 'Windows O/S', 'category_id' => '5','created_at' => Carbon::now()],
            ['name' => 'Mac O/S', 'category_id' => '5','created_at' => Carbon::now()],
            ['name' => 'General Hardware Questions', 'category_id' => '5','created_at' => Carbon::now()],
            ['name' => 'Crypto Currency', 'category_id' => '5','created_at' => Carbon::now()],
            ['name' => 'Building a Website', 'category_id' => '5','created_at' => Carbon::now()],
            ['name' => 'Starting an online business', 'category_id' => '5','created_at' => Carbon::now()],
            ['name' => 'Artificial Intelligence', 'category_id' => '5','created_at' => Carbon::now()],
            ['name' => 'Socializing', 'category_id' => '6','created_at' => Carbon::now()],
            ['name' => 'Safety', 'category_id' => '6','created_at' => Carbon::now()],
            ['name' => 'Local/Regional Politics', 'category_id' => '6','created_at' => Carbon::now()],
            ['name' => 'Local/Regional Politics', 'category_id' => '6','created_at' => Carbon::now()],
            ['name' => 'Familiy Life', 'category_id' => '6','created_at' => Carbon::now()],
            ['name' => 'Graphic Design', 'category_id' => '7','created_at' => Carbon::now()],
            ['name' => 'User Experience (UX)', 'category_id' => '7','created_at' => Carbon::now()],
            ['name' => 'Architecture', 'category_id' => '7','created_at' => Carbon::now()],
            ['name' => 'Robotics', 'category_id' => '8','created_at' => Carbon::now()],
            ['name' => 'Agricultural Equipment', 'category_id' => '8','created_at' => Carbon::now()],
            ['name' => 'Manufacturing', 'category_id' => '8','created_at' => Carbon::now()],
            ['name' => 'Weddings', 'category_id' => '9','created_at' => Carbon::now()],
            ['name' => 'Planning 101', 'category_id' => '9','created_at' => Carbon::now()],
            ['name' => 'Corporate', 'category_id' => '9','created_at' => Carbon::now()],
            ['name' => 'Formal Events', 'category_id' => '9','created_at' => Carbon::now()],
            ['name' => 'Music/Festivals', 'category_id' => '9','created_at' => Carbon::now()],
            ['name' => 'Boardgames', 'category_id' => '10','created_at' => Carbon::now()],
            ['name' => 'PC/Mac Games', 'category_id' => '10','created_at' => Carbon::now()],
            ['name' => 'Console Games (Xbox, PS, Nintendo, etc.)', 'category_id' => '10','created_at' => Carbon::now()],
            ['name' => 'Retro Games', 'category_id' => '10','created_at' => Carbon::now()],
            ['name' => 'Plumbing', 'category_id' => '11','created_at' => Carbon::now()],
            ['name' => 'Electrical', 'category_id' => '11','created_at' => Carbon::now()],
            ['name' => 'DIY Projects', 'category_id' => '11','created_at' => Carbon::now()],
            ['name' => 'Remodeling', 'category_id' => '11','created_at' => Carbon::now()],
            ['name' => 'Painting', 'category_id' => '11','created_at' => Carbon::now()],
            ['name' => 'Heating and A/C', 'category_id' => '11','created_at' => Carbon::now()],
            ['name' => 'Roofing', 'category_id' => '11','created_at' => Carbon::now()],
            ['name' => 'Remodeling', 'category_id' => '11','created_at' => Carbon::now()],
            ['name' => 'Stock Market', 'category_id' => '12','created_at' => Carbon::now()],
            ['name' => 'Real Estate', 'category_id' => '12','created_at' => Carbon::now()],
            ['name' => 'Taxes', 'category_id' => '12','created_at' => Carbon::now()],
            ['name' => 'Retirement Planning', 'category_id' => '12','created_at' => Carbon::now()],
            ['name' => 'Personal Finance', 'category_id' => '12','created_at' => Carbon::now()],
            ['name' => 'Coaching', 'category_id' => '13','created_at' => Carbon::now()],
            ['name' => 'Building Teams', 'category_id' => '13','created_at' => Carbon::now()],
            ['name' => 'Culture', 'category_id' => '13','created_at' => Carbon::now()],
            ['name' => 'Remote Teams', 'category_id' => '13','created_at' => Carbon::now()],
            ['name' => 'Learning an Instrument', 'category_id' => '14','created_at' => Carbon::now()],
            ['name' => 'Recording/Studios', 'category_id' => '14','created_at' => Carbon::now()],
            ['name' => 'Teaching', 'category_id' => '14','created_at' => Carbon::now()],
            ['name' => 'Music History', 'category_id' => '14','created_at' => Carbon::now()],
            ['name' => 'Artificial Intelligence', 'category_id' => '15','created_at' => Carbon::now()],
            ['name' => 'AR/VR', 'category_id' => '15','created_at' => Carbon::now()],
            ['name' => 'Self-Driving Vehicles', 'category_id' => '15','created_at' => Carbon::now()],
            ['name' => 'Toddlers', 'category_id' => '16','created_at' => Carbon::now()],
            ['name' => 'Socializing', 'category_id' => '16','created_at' => Carbon::now()],
            ['name' => 'Babies', 'category_id' => '16','created_at' => Carbon::now()],
            ['name' => 'Kid Safety', 'category_id' => '16','created_at' => Carbon::now()],
            ['name' => 'Education', 'category_id' => '16','created_at' => Carbon::now()],
            ['name' => 'Home Schooling', 'category_id' => '16','created_at' => Carbon::now()],
            ['name' => 'Training', 'category_id' => '17','created_at' => Carbon::now()],
            ['name' => 'Vets', 'category_id' => '17','created_at' => Carbon::now()],
            ['name' => 'General', 'category_id' => '17','created_at' => Carbon::now()],
            ['name' => 'Dog Ownership', 'category_id' => '17','created_at' => Carbon::now()],
            ['name' => 'Cat Ownership', 'category_id' => '17','created_at' => Carbon::now()],
            ['name' => 'Small Miscellaneous Pets', 'category_id' => '17','created_at' => Carbon::now()],
            ['name' => 'Exotic Animals', 'category_id' => '17','created_at' => Carbon::now()],
            ['name' => 'Friends', 'category_id' => '18','created_at' => Carbon::now()],
            ['name' => 'Dating', 'category_id' => '18','created_at' => Carbon::now()],
            ['name' => 'Marriage', 'category_id' => '18','created_at' => Carbon::now()],
            ['name' => 'Co-workers/Business', 'category_id' => '18','created_at' => Carbon::now()],
            ['name' => 'Family', 'category_id' => '18','created_at' => Carbon::now()],
            ['name' => 'Roadtrips', 'category_id' => '19','created_at' => Carbon::now()],
            ['name' => 'Beach Destinations', 'category_id' => '19','created_at' => Carbon::now()],
            ['name' => 'Asia', 'category_id' => '19','created_at' => Carbon::now()],
            ['name' => 'Europe', 'category_id' => '19','created_at' => Carbon::now()],
            ['name' => 'Africa', 'category_id' => '19','created_at' => Carbon::now()],
            ['name' => 'Exotic Destinations', 'category_id' => '19','created_at' => Carbon::now()],
            ['name' => 'North America', 'category_id' => '19','created_at' => Carbon::now()],
            ['name' => 'South America', 'category_id' => '19','created_at' => Carbon::now()],
            ['name' => 'Travel Agents', 'category_id' => '19','created_at' => Carbon::now()],
            ['name' => 'Becoming a Writer', 'category_id' => '20','created_at' => Carbon::now()],
            ['name' => 'Poetry', 'category_id' => '20','created_at' => Carbon::now()],
            ['name' => 'Creating Web/Digital Print', 'category_id' => '20','created_at' => Carbon::now()],
            ['name' => 'Copyrighting', 'category_id' => '20','created_at' => Carbon::now()],
            ['name' => 'Fiction', 'category_id' => '20','created_at' => Carbon::now()],
            ['name' => 'Non-Fiction', 'category_id' => '20','created_at' => Carbon::now()],
            ['name' => 'Historical Fiction/Non-Fiction', 'category_id' => '20','created_at' => Carbon::now()],
        ]);
    }
}
